### ISSUE TITLE
DB error error returned from database: bigint out of range

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/mercury#146]
**What happened**:

```
➜  mercury git:(main) ✗ curl -X POST http://localhost:8116 -H 'Content-Type: application/json' -d @- <<BODY
{
  "id": 42,
  "jsonrpc": "2.0",
  "method": "get_block_info",
  "params": [
    {
      "block_number": null,
      "block_hash": null
    }
  ]
}
BODY
{"jsonrpc":"2.0","error":{"code":-32000,"message":"Mercury Rpc Error code -11005, error DB error error returned from database: bigint out of range"},"id":42}%  
```

**What you expected to happen**:

Return latest block

**How to reproduce it (as minimally and precisely as possible)**:

Start postgres:
```
docker run -p 5432:8432 -v /home/kuzi/projects/mercury/devtools/create_table/create_table.sql:/docker-entrypoint-initdb.d/create_tables.sql -e POSTGRES_USER=postgres -e POSTGRES_DB=mercury -e POSTGRES_PASSWORD=123456 postgres:alpine
```

Use this mainnet config: https://gist.github.com/Kuzirashi/7be03450748ed41e3aba81a589d33aa1

**Anything else we need to know?**:

**Environment**:

- Mercury version or commit hash (`git log -1`): a01046229a18dbe8392df0cff542553c13062b41
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux DESKTOP-H3DBUQR 4.19.104-microsoft-standard SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by KaoImin** [comment]
The mercury with relational database is under development, we suggest you use the v0.1.0 version. Version 0.2.0, which uses relational database as storage, is expected to be released in September. Thanks.

**Comment by Kuzirashi** [comment]
v0.1.0 works indeed. :)
