### ISSUE TITLE
Remote Nodes

### ISSUE THREAD

**Issue by x777** [nervosnetwork/mercury#291]
Hi, can anybody provide a list of remote mercury nodes for testnet and mainnet? Thx!

**Comment by rev-chaos** [comment]
> Hi, can anybody provide a list of remote mercury nodes for testnet and mainnet? Thx!

For Testnet
mercury-rpc: https://mercury-testnet.ckbapp.dev/ 
ckb-rpc: https://mercury-testnet.ckbapp.dev/rpc 
indexer-rpc: https://mercury-testnet.ckbapp.dev/indexer

For Mainnet
mercury-rpc: https://mercury-mainnet.ckbapp.dev/ 
ckb-rpc: https://mercury-mainnet.ckbapp.dev/rpc 
indexer-rpc: https://mercury-mainnet.ckbapp.dev/indexer

Remote nodes do not guarantee high availability and high performance. 
If you want to use Mercury in a production project, please deploy and run Mercury by yourself.

**Comment by KaoImin** [comment]
The remote node info can be shown in wiki.

**Comment by x777** [comment]
> > Hi, can anybody provide a list of remote mercury nodes for testnet and mainnet? Thx!
> 
> For Testnet mercury-rpc: https://mercury-testnet.ckbapp.dev/ ckb-rpc: https://mercury-testnet.ckbapp.dev/rpc indexer-rpc: https://mercury-testnet.ckbapp.dev/indexer
> 
> For Mainnet mercury-rpc: https://mercury-mainnet.ckbapp.dev/ ckb-rpc: https://mercury-mainnet.ckbapp.dev/rpc indexer-rpc: https://mercury-mainnet.ckbapp.dev/indexer
> 
> These remote nodes do not guarantee high availability and high performance. If you want to use Mercury in a production project, please deploy and run Mercury by yourself.

What preferred requirements for deployment of own node?

**Comment by KaoImin** [comment]
> > > Hi, can anybody provide a list of remote mercury nodes for testnet and mainnet? Thx!
> > 
> > 
> > For Testnet mercury-rpc: https://mercury-testnet.ckbapp.dev/ ckb-rpc: https://mercury-testnet.ckbapp.dev/rpc indexer-rpc: https://mercury-testnet.ckbapp.dev/indexer
> > For Mainnet mercury-rpc: https://mercury-mainnet.ckbapp.dev/ ckb-rpc: https://mercury-mainnet.ckbapp.dev/rpc indexer-rpc: https://mercury-mainnet.ckbapp.dev/indexer
> > These remote nodes do not guarantee high availability and high performance. If you want to use Mercury in a production project, please deploy and run Mercury by yourself.
> 
> What preferred requirements for deployment of own node?

See here https://github.com/nervosnetwork/mercury/tree/dev#recommended-hardware-1
