### ISSUE TITLE
当mercury 启动失败时，没有任何错误信息？

### ISSUE THREAD

**Issue by jiangxianliang007** [nervosnetwork/mercury#311]
![image](https://user-images.githubusercontent.com/24754263/142370975-367780b3-63b7-4ae9-8b7c-f67411664c46.png)
![image](https://user-images.githubusercontent.com/24754263/142370767-7c4de2b2-3903-4acf-a1e5-676b963bdb7c.png)

版本号：mercury:v0.2.0-beta.4  
部署好mercury 后，它一直在重启，而且没有生成日志目录，没有任何日志的情况下，该怎么判断它是什么原因导致启动失败？
有什么方法把启动失败的信息打印出来？
```
[log_config]
log_level = "error"
auto_split_log_file = true
log_path = "./free-space/mainnet/log"
```
free-space/mainnet/  目录没有生产log 文件夹

**Comment by KaoImin** [comment]
The v0.2.0-beta.4 version changes some configurations, do you use the latest deploy script power by @zhengjianhui ?
