### ISSUE TITLE
Improper spelling of "frozen" in terminology.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/mercury#335]
**What happened**:

In the terminology used and in the API, the key "freezed" is used. This is the incorrect spelling in modern usage.

**What you expected to happen**:

The correct spelling is "frozen".

- Mercury version or commit hash (`git log -1`): v0.2.0 (stable)

**Comment by EthanYuan** [comment]
First of all thank you for pointing out this spelling error. We used a verb form.

If we modify directly based on the stable version of v0.2.0, it will cause breaking changes, and the SDK needs to be modified accordingly. Any suggestions for this situation?

**Comment by jordanmack** [comment]
If I understand correctly, Mercury deployments are low, but it is already being used in production environments for some exchanges. My suggestion would be to leave it as is until the next major stable version that contains other breaking changes.

**Comment by EthanYuan** [comment]
I agree with your suggestion very much, thank you. @jordanmack

**Comment by EthanYuan** [comment]
https://github.com/nervosnetwork/mercury/pull/391
