### ISSUE TITLE
Need to update the ckb version in docker-compose file.

### ISSUE THREAD

**Issue by hawkeye222** [nervosnetwork/mercury#408]
There is a hardfork of ckb mainnet on version v0.103.0 , but the ckb version in mercury docker-compose file is still v0.101.0 .

**Comment by EthanYuan** [comment]
Mercury (versions after 0.2.0) is compatible with ckb v0.103, so we directly updated the version of the ckb component in docker-compose.yml in each branch.

Thanks for pointing this out.
